### ISSUE TITLE
remove trailing slashes from environment variables' values

### ISSUE THREAD

**Issue by thomasstxyz** [2110781006/fppss-frontend#13]
At the moment you must have trailing slashes in the URIs of the environment variables FPPSS_REST_URL and FPPSS_KEYCLOAK_URL.

Let's change it so you have this trailing slash within the code!

Example:

```yaml
        - name: FPPSS_REST_URL
          value: "https://example.com/api/v1/"  <-- put this trailing slash in the code itself!
        - name: FPPSS_KEYCLOAK_URL
          value: "https://example.com/auth/"  <-- this as well!

```
